// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAgent() {
  return window['go']['main']['App']['StartAgent']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}
