// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';

export function GetConfig():Promise<agent.Config>;

export function GetStatus():Promise<string>;

export function HideWindow():Promise<void>;

export function SaveConfig(arg1:agent.Config):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAgent():Promise<void>;

export function StopAgent():Promise<void>;
